Button design
simple-icons/simple-icons-website pull request #123
Opened 2021-10-17 20:32 UTC by jorgeamadosoria

Complying with @fbernhart comment, this PR removes the margin between the buttons but keep a thin border of separation.

- Removed the internal borders for button groups.
- Rounded only the first and last buttons in the relevant corners (not internal)
- To simplify the CSS, I had to move sorting relevance to the middle of the sort group, because it is sometimes hidden and the last-of-type selector does not work in that case.

2021-10-19 18:48 UTC, ericcornelissen commented on public/stylesheet.css
> +  border-right: 0.1rem solid var(--color-button-border);
This can be simplified to avoid repetition

```suggestion
  border: 0.1rem solid var(--color-button-border);
  border-left-width: 0;
```

With this change you can also have just `border-left: 0.1rem` in the `:first-of-type` ruleset.

2021-10-19 18:48 UTC, ericcornelissen commented on public/stylesheet.css
> +  border: 0.1rem solid var(--color-button-border);
Did you intentionally leave out the `border-radius` here?

2021-10-19 18:48 UTC, ericcornelissen commented on public/index.pug
> -                path(d="M9.219 18.857H6.648V.429A.414.414 0 0 0 6.219 0H3.648a.418.418 0 0 0-.308.121.418.418 0 0 0-.121.308v18.428H.648a.4.4 0 0 0-.402.268c-.071.17-.04.326.094.469l4.286 4.287c.098.
I'm not convinced this is the solution we should go with, the way the button order changes when searching as a result of this is confusing in my opinion.

We could insert the button for sorting by relevance only when there's an active query. Alternatively we could use classes here to overwrite (or replace) the use of `:last-xxx`. What do you think @jorgeamadosoria?

2021-10-19 18:48 UTC, ericcornelissen commented on public/stylesheet.css
> +.control__button:last-of-type:not(.hidden) {
The last part of this selector doesn't do anything as far as I can tell.

```suggestion
.control__button:last-of-type {
```

2021-10-19 18:48 UTC, ericcornelissen commented on public/stylesheet.css
> +  margin-right: 0;
I don't think this is necessary, nor the `margin-left` in the `:first-of-type` ruleset.

2021-10-19 20:49 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border: 0.1rem solid var(--color-button-border);
no. Good catch

2021-10-19 20:50 UTC, jorgeamadosoria commented on public/index.pug
> -                path(d="M9.219 18.857H6.648V.429A.414.414 0 0 0 6.219 0H3.648a.418.418 0 0 0-.308.121.418.418 0 0 0-.121.308v18.428H.648a.4.4 0 0 0-.402.268c-.071.17-.04.326.094.469l4.286 4.287c.098.
I don't think this is a big issue, but I see your point.
I don't know if inserting the button on an active query is going to work, but maybe a CSS class will. I'll try that approach

2021-10-19 20:51 UTC, jorgeamadosoria commented on public/stylesheet.css
> +.control__button:last-of-type:not(.hidden) {
that is true. I first tried to use this to exclude the hidden button before changing its position. We can remove it.

2021-10-19 20:51 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  margin-right: 0;
this may go away if we build a dedicated CSS class anyways.

2021-10-20 02:01 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border-right: 0.1rem solid var(--color-button-border);
ok

2021-10-20 02:01 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border: 0.1rem solid var(--color-button-border);
restored

2021-10-20 02:02 UTC, jorgeamadosoria commented on public/index.pug
> -                path(d="M9.219 18.857H6.648V.429A.414.414 0 0 0 6.219 0H3.648a.418.418 0 0 0-.308.121.418.418 0 0 0-.121.308v18.428H.648a.4.4 0 0 0-.402.268c-.071.17-.04.326.094.469l4.286 4.287c.098.
reworked by applying a class in search.js whenever the search string changes.

2021-10-20 04:31 UTC, jorgeamadosoria commented
ok, all suggestions worked into this PR.

2021-10-21 16:12 UTC, ericcornelissen commented on public/stylesheet.css
> +  margin-right: 0;
Looks like it's still here 🤔

2021-10-21 16:12 UTC, ericcornelissen commented on public/stylesheet.css
> +  border-bottom-left-radius: var(--border-radius-small);
This looks off 🤔

2021-10-21 17:52 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border-bottom-left-radius: var(--border-radius-small);
make a suggestion? other than removing the comment, I don't know what looks off there.

2021-10-22 00:48 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border-bottom-left-radius: var(--border-radius-small);
I reworked this to reduce the class attribute. I changed the border-left for border-left-width, that way all the other border properties are inherited from control__button.
Maybe that looks better? It's certainly less redundant and shorter.

2021-10-22 00:54 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  margin-right: 0;
it's not anymore

2021-10-22 21:23 UTC, ericcornelissen requested changes

2021-10-22 21:23 UTC, ericcornelissen commented on public/scripts/search.js
> +      domUtils.toggleClass($orderByColor, 'last__button');
Toggle here doesn't work with the current implementation because this if-branch is executed for every keystroke. As a result, after typing one character it's good, after typing another it's wrong, etc. (ignoring the de-bouncing for simplicity)

2021-10-24 17:04 UTC, ericcornelissen reviewed
Functionality works as expected now, nice work :+1: Got two things that can be improved in the code

2021-10-24 17:04 UTC, ericcornelissen commented on public/scripts/dom-utils.js
> +}
Should this be removed, it seems to not be used anymore?

2021-10-24 17:04 UTC, ericcornelissen commented on tests/dom-utils.test.js
> +});
This is the exact same test twice.

Also, the add and remove class helpers should probably be tested as well/instead.

2021-10-24 17:05 UTC, ericcornelissen commented on public/stylesheet.css
> +  border-bottom-left-radius: var(--border-radius-small);
The main reason I commented here is because `// comment` is not a comment in CSS.

2021-10-24 17:19 UTC, jorgeamadosoria commented on public/stylesheet.css
> +  border-bottom-left-radius: var(--border-radius-small);
It's fine, it doesn't matter anymore

2021-10-24 17:20 UTC, jorgeamadosoria commented on public/scripts/dom-utils.js
> +}
It's not used anymore, but I have plabs for it elsewhere. And this being an utils class, I thought that it doesn't hurt to add it now since it's already there

2021-10-24 17:22 UTC, jorgeamadosoria commented on tests/dom-utils.test.js
> +});
Add and remove should be added, yes.
I have issues resolving " and ' with prettier, and that creates annoying merge conflicts where both branches are the same. Hence why you would find this kond of duplications.

2021-10-24 19:32 UTC, ericcornelissen commented on public/scripts/dom-utils.js
> +}
Feel free to keep it then, your call

2021-10-24 23:12 UTC, jorgeamadosoria commented on public/scripts/dom-utils.js
> +}
I will for now, thanks. It will help later on in some refacts I plan on doing soon when I'm done with the compact design.

2021-10-24 23:24 UTC, jorgeamadosoria commented on tests/dom-utils.test.js
> +});
Done

2021-10-25 20:09 UTC, ericcornelissen approved these changes
Feel free to merge this as you see fit @jorgeamadosoria

2021-10-25 20:09 UTC, ericcornelissen commented on tests/dom-utils.test.js
> -    hideElement($el);
I don't understand why you made this change. What's the point of combining the two test case? Plus, if there's just one test case, why even have the `describe` and `beforeEach`?

My motivation for originally writing it as two separate tests is because it's testing two separate things. I don't care if you want to change the approach, but this Pull Request seems like an odd place to do that.

2021-10-25 20:09 UTC, ericcornelissen commented on tests/dom-utils.test.js
> -    expect($el.removeAttribute).toHaveBeenCalledWith('aria-hidden');
I don't understand why you made this change. What's the point of combining the two test case? Plus, if there's just one test case, why even have the `describe` and `beforeEach`?

My motivation for originally writing it as two separate tests is because it's testing two separate things. I don't care if you want to change the approach, but this Pull Request seems like an odd place to do that.

2021-10-25 20:12 UTC, jorgeamadosoria commented on tests/dom-utils.test.js
> -    hideElement($el);
the two things are not really separate things. They can't be called by themselves: As a matter of fact, if they were to be called separate from each other this test would throw an exception, as it should since that shouldn't happen.We are testing the functionality of hideElement, which should have the two success criteria happening together. 
Agreed in that this PR is not the best place for this, but I was adding the other tests and I saw a chance to refactor this here.

2021-10-25 20:14 UTC, jorgeamadosoria commented on tests/dom-utils.test.js
> -    expect($el.removeAttribute).toHaveBeenCalledWith('aria-hidden');
same comment as the previous conversation.

2021-10-25 20:14 UTC, merged