Use bot token for releases
simple-icons/simple-icons-website pull request #322
Opened 2024-04-08 00:50 UTC by LitoMore

2024-04-09 20:49 UTC, mondeja requested changes

2024-04-09 20:49 UTC, mondeja commented on .github/workflows/publish.yml
> -          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
The build process uses the `GITHUB_TOKEN` environment variable because needs to call the API several times. Would you mind to use the bot token here?

2024-04-10 13:26 UTC, mondeja commented on .github/workflows/publish.yml
> +          repositories: 'simple-icons,simple-icons-website'
Why this line is needed?

2024-04-10 15:29 UTC, LitoMore commented on .github/workflows/publish.yml
> +          repositories: 'simple-icons,simple-icons-website'
See https://github.com/actions/create-github-app-token?tab=readme-ov-file#repositories.

2024-04-11 19:46 UTC, mondeja commented on .github/workflows/publish.yml
> +          repositories: 'simple-icons,simple-icons-website'
But we are accessing the public part of the API for `simple-icons/simple-icons`. It is needed to explicitly define the repos in that case?

2024-04-11 20:19 UTC, LitoMore commented on .github/workflows/publish.yml
> +          repositories: 'simple-icons,simple-icons-website'
Not exactly. We are using this API below for read organization members:

```js
const siOrgMembers = await githubAPI.GET('/orgs/simple-icons/members');
```

But you're right. This data is used to generate SEO `application/ld+json` information. Our private members may not want to appear on the list.

2024-04-11 20:21 UTC, LitoMore commented on .github/workflows/publish.yml
> +          repositories: 'simple-icons,simple-icons-website'
You could ignore the failing CI, it caused by the pull request was created from my forked repository.

See https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions#using-secrets-in-a-workflow

2024-04-12 10:18 UTC, mondeja approved these changes

2024-04-12 10:18 UTC, merged